linters:
  enable:
    - dogsled
    - dupl
    - gofmt
    - goimports
    - gosec
    - misspell
    - nakedret
    - stylecheck
    - unconvert
    - unparam
    - whitespace
  disable:
    - errcheck
    - gosimple
    - staticcheck
    - ineffassign
    - unused
issues:
  exclude:
    - composites
  exclude-rules:
  - linters:
    - dupl
    path: _test\.go
